import fetch from 'node-fetch';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read UUIDs from the file generated by scanUUIDs.js
const imageUUIDs = JSON.parse(fs.readFileSync('imageUUIDs.json', 'utf-8'));

async function fetchImageDimensions(uuid) {
  const response = await fetch(`https://ucarecdn.com/${uuid}/-/json/`);
  const data = await response.json();
  return { width: data.width, height: data.height };
}

async function prefetchDimensions() {
  const dimensions = {};
  for (const uuid of imageUUIDs) {
    try {
      dimensions[uuid] = await fetchImageDimensions(uuid);
      console.log(`Fetched dimensions for UUID: ${uuid}`);
    } catch (error) {
      console.error(`Error fetching dimensions for UUID: ${uuid}`, error);
    }
  }
  fs.writeFileSync('src/layouts/components/imageDimensions.json', JSON.stringify(dimensions, null, 2));
  console.log(`Dimensions fetched and saved for ${Object.keys(dimensions).length} images.`);
}

prefetchDimensions().catch(console.error);